spring:
  application:
    name: Blogging

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Xoja@8008
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

